### ISSUE TITLE
ERROR: This tool requires libclamav with functionality level 124 or higher (current f-level: 123)

### ISSUE THREAD

**Issue by bigdatastream** [Cisco-Talos/clamav#324]
We have setup 2 virus checker lambdas in nodejs which uses clamav

1. the first lambda updates the virus definitions every 6 hours
2. the second performs the virus checks on the file we pass it

The second lambda started failing recently with the error below when scanning a file. This happens when the virus definitions file goes out of date. Not sure if the first lambda threw an error or was simply out of date for this error to occur. We fetch every 6 hours using cloudwatch cron schedule

Why would the libclamav suddenly break. Why can't it use the previous virus definitions file? This broke our production environment, so please provide us a solution asap

ERROR: This tool requires libclamav with functionality level 124 or higher (current f-level: 123)

2021-07-16T17:56:59.454Z 2ceb4e73-dc71-4bb4-9f32-4fc7a63682f5 ERROR Invoke Error {"errorType":"Error","errorMessage":"Command failed: ./clamd -c ./clamd.conf\nERROR: This tool requires libclamav with functionality level 124 or higher (current f-level: 123)\n","status":1,"signal":null,"output":[null,{"type":"Buffer","data":[]},{"type":"Buffer","data":[69,82,82,79,82,58,32,84,104,105,115,32,116,111,111,108,32,114,101,113,117,105,114,101,115,32,108,105,98,99,108,97,109,97,118,32,119,105,116,104,32,102,117,110,99,116,105,111,110,97,108,105,116,121,32,108,101,118,101,108,32,49,50,52,32,111,114,32,104,105,103,104,101,114,32,40,99,117,114,114,101,110,116,32,102,45,108,101,118,101,108,58,32,49,50,51,41,10]}],"pid":544,"stdout":{"type":"Buffer","data":[]},"stderr":{"type":"Buffer","data":[69,82,82,79,82,58,32,84,104,105,115,32,116,111,111,108,32,114,101,113,117,105,114,101,115,32,108,105,98,99,108,97,109,97,118,32,119,105,116,104,32,102,117,110,99,116,105,111,110,97,108,105,116,121,32,108,101,118,101,108,32,49,50,52,32,111,114,32,104,105,103,104,101,114,32,40,99,117,114,114,101,110,116,32,102,45,108,101,118,101,108,58,32,49,50,51,41,10]},"stack":["Error: Command failed: ./clamd -c ./clamd.conf","ERROR: This tool requires libclamav with functionality level 124 or higher (current f-level: 123)",""," at checkExecSyncError (child_process.js:635:11)"," at execSync (child_process.js:671:15)"," at runDaemon (/var/task/clamav-service.js:37:9)"," at runMicrotasks (<anonymous>)"," at processTicksAndRejections (internal/process/task_queues.js:97:5)"," at async runDaemon (/var/task/clamav-service.js:44:9)"," at async runDaemon (/var/task/clamav-service.js:44:9)"," at async runDaemon (/var/task/clamav-service.js:44:9)"," at async Runtime.scanFile [as handler] (/var/task/handler.js:24:5)"]}

**Comment by bigdatastream** [comment]
Hi Micah

Sorry for not replying earlier.

Actually your reply helped us to identify the issue. We are using clamav in
a lambda setup and found the clamav lib in the lambda and the underlying
lambda layer. When it was moved to the layer we forgot to remove the
dependency in the main lambda.

The error confused us initially but your reply helped us realise why we
have a conflict

Thanks
